# Standard configuration
# Including MariaDB, MediaWiki, Matomo, Logstash, ElasticSearch, Kibana
# Contains frequently-used micro-services of a basic XLP system

version: '2'
services:
  mariadb:
    image: mariadb:10.3
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=W2qgpsLtQt
    volumes:
    - /data/xlpsystem/mariadb/:/var/lib/mysql
    
  mediawiki:
    image: xlpsystem/mediawiki:20180827140844
    restart: always
    ports:
    - 81:80
    volumes:
    - /data/xlpsystem/mediawiki:/xlp_data
    - /data/xlpsystem/mediawiki_dev:/xlp_dev
    depends_on:
    - mariadb
    - matomo
    - elasticsearch
    - parsoid
    
  matomo:
    image: xlpsystem/matomo:20180820163542
    restart: always
    ports:
    - 82:80
    volumes:
    - /data/xlpsystem/matomo:/var/www/html
    depends_on:
    - mariadb
  
  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 6.6.1
    volumes:
    - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    - ./logstash/depends:/depends
    ports:
    - "5000:5000"
    - "9600:9600"
    environment:
    - LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
    - elasticsearch
  
  parsoid:
    image: thenets/parsoid:0.9.0
    restart: always
    environment:
    - PARSOID_DOMAIN_localhost=http://mediawiki/api.php
    ports:
    - 8000:8000
    
  elasticsearch:
    image: xlpsystem/elasticsearch:20180822142218
    volumes:
    - /data/xlpsystem/elasticsearch:/usr/share/elasticsearch/data
    environment:
    - discovery.type=single-node
    - bootstrap.memory_lock=true
    - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    
  kibana:
    image: xlpsystem/kibana:20180821233221
    ports:
    - 84:5601
    depends_on:
    - elasticsearch
